name: VSR
channels:
  - defaults
  - pytorch
dependencies:
  # - torch==1.3.0.post2
  - python=3.8
  - numpy
  - scikit-image
  - tqdm
  - ipykernel
  - matplotlib 
  - tensorboard 
  - ipykernel
  - pandas
  - Cython
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu113
    - scikit-image
    - torch==1.12.1+cu113 
    - torchvision==0.13.1+cu113 
    - pytorch-ssim==0.1
    - opencv-python==4.5.1.48
    # - torch==1.4.0
    # - torchvision==0.5.0